### ISSUE TITLE
Feature: Repeat notifications

### ISSUE THREAD

**Issue by rwjack** [healthchecks/healthchecks#686] opened 2022-08-03 06:15 UTC
Hey,

I thought it would be a great idea if we could have repeating notifications.

eg. if one of the checks fails, have the option to repeat the notification after X minutes/hours/days, to the same or additional notification methods, if the check is not resolved within given X timeframe.

**Comment by cuu508** [comment] 2022-08-03 06:18
Duplicate of #510

**Closed by cuu508** 2022-08-03 06:18 UTC

**Comment by rwjack** [comment] 2022-08-03 08:54
Now I see others are having the same issue.

1 hour/1 day and only via email is too rigid.

The code to send notifications is basically there, it should just have the ability to re-send the notification to slack for example.

From my point of view the only thing that would need to be implemented for this to work is some sort of timer function. I'm not sure how hard it would be to have a timer start for every failed job, but it definitely would be a nice addition, especially for notification methods other than email, if/when you have the time of course.
