### ISSUE TITLE
Feature request: Add other HTTP verbs, separate up / down data fields, to webhook

### ISSUE THREAD

**Issue by Grayda** [healthchecks/healthchecks#254] opened 2019-05-20 03:14 UTC
I'm using [Cachet](https://cachethq.io) and HC to automate my public-facing status page. HC's webhook integration allows you to POST data, but Cachet requires you to PUT data instead. Also it can only accept a numeric status (e.g. 1 = OK, 2 = Performance issues, 3 = Minor outage, 4 = Major outage) and not a string ("up" or "down")

To get around this I've [modified](https://github.com/Auroras-live/Cachet/commit/6357e971348927e57bf36d3a6492939d1f244f04) [Cachet](https://github.com/Auroras-live/Cachet/commit/9a0e18cf3d016042f648bc50d0e5f9d01802155a) to accept POST commands in place of PUT commands, and have set up an IF statement so that "up" = 1, and "down" = 4.

I'd love it if HC would support more HTTP verbs (e.g. PUT, PATCH, DELETE etc.), and if you could send separate data for up and down events, so for the up endpoint I could send `{"status": 1}`, and for the down endpoint send `{"status": 4}`

**Comment by cuu508** [comment] 2019-05-20 20:18
Duplicate of #249

**Closed by cuu508** 2019-05-20 20:18 UTC
