### ISSUE TITLE
Mastodon notifications

### ISSUE THREAD

**Issue by bt90** [healthchecks/healthchecks#731] opened 2022-11-12 17:08 UTC
This one should be quite easy as apprise just added support: https://github.com/caronc/apprise/pull/747

Just making sure that we don't miss it in the release notes once the library version is bumped.

**Comment by bt90** [comment] 2022-11-15 20:04
Apprise v1.2.0 has been released with Mastodon support.

**Comment by cuu508** [comment] 2022-12-19 11:50
Duplicate of #167

**Closed by cuu508** 2022-12-19 11:50 UTC
