### ISSUE TITLE
Implementing a "warning" status between Success and Fail

### ISSUE THREAD

**Issue by Ailothaen** [healthchecks/healthchecks#559] opened 2021-09-06 19:42 UTC
Hello,

A feature I particularly like about healthchecks is the ability to signal failures ( https://healthchecks.io/docs/signaling_failures/ ). However, sometimes, a script may end without a critical error, but still have significant conditions that are worthy to be monitored.

I would therefore suggest the creation of a "warning" status, between successes and failures. For example, it would be triggered using an URL like this: `https://hc-ping.com/your-uuid-here/warning`

A bonus feature about this (but which requires potentially a design change) is to be able to choose which status codes trigger an success condition, and which ones trigger a warning and a failure. So for example, 0 to 10 would be OK, 11 to 20 would be Warning, and everything else be a failure...

**Comment by ep1cman** [comment] 2021-09-09 01:48
This would be increadibly useful, especially selecting which exit codes are a failure and which are a warning on the backend. 

I currently used healthchecks to ensure my daily backups complete using a tool called `restic`. It will give exit code `1` for fatal errors but `3` for backups that have succeeded but missed some files. It would be great if this could be logged as a warning in healthchecks, but not fail the check.

**Comment by BerriJ** [comment] 2022-01-13 15:11
This is a duplicate of https://github.com/healthchecks/healthchecks/issues/227

However, I'm also eagerly waiting for this feature.

**Comment by cuu508** [comment] 2022-01-17 11:23
Indeed it's a duplicate, closing.

**Closed by cuu508** 2022-01-17 11:23 UTC
Labels: feature
