### ISSUE TITLE
Missing last duration times

### ISSUE THREAD

**Issue by warwickmm** [healthchecks/healthchecks#753] opened 2022-12-17 22:56 UTC
Previously, I was able to see the duration times as documented [here](https://healthchecks.io/docs/measuring_script_run_time/):

![image](https://user-images.githubusercontent.com/17345532/208268802-ab920d06-5c85-4b14-8437-f9e9578c1047.png)

However, starting a few months ago, I no longer see the duration times:

![image](https://user-images.githubusercontent.com/17345532/208268814-e1dab7dd-ba34-47c7-b6f4-47f58df39f3c.png)

If I click on the "last ping", I do see a duration:

![image](https://user-images.githubusercontent.com/17345532/208268829-86137211-34d4-4320-9f19-65c718548fa8.png)

Similarly, if I click on "show details", I do see durations for all the events.  Has the duration been removed from the main page, or am I doing something incorrectly?

**Comment by cuu508** [comment] 2022-12-18 10:09
Thanks for reporting this. This was caused by a bug I introduced when adding [Run IDs](https://blog.healthchecks.io/2022/11/using-run-ids-to-track-run-times-of-overlapping-jobs/). I've now fixed the bug – you should start seeing durations again for the future pings.

The bug was in custom code that runs on hc-ping.com (not part of this repository, so no new commits here). The bug was to do with comparing run IDs. If the run IDs for both the "start" and the "success" pings are NULL, then we're comparing NULL <--> NULL, and Postgres is a little funky there:


```
hc=# select 1 = 1;
 ?column? 
----------
 t
(1 row)

hc=# select NULL = NULL;
 ?column? 
----------
 
(1 row)
```

**Closed by cuu508** 2022-12-18 10:09 UTC
