### ISSUE TITLE
Recuring failure notifications for checks configured using a cron schedule

### ISSUE THREAD

**Issue by PAI5REECHO** [healthchecks/healthchecks#665] opened 2022-06-09 22:34 UTC
I have a check that sends out notifications for backups that fail to run at an expected cron schedule. Once a check configured to use a cron schedule enters a **Down** state it does not send additional notifications for ever subsequent failure thereafter. I would like it to continue to send notifications at every cron interval so I don't forget about the failure state. #510 is kinda close but not really. I get that the way healthchecks works is that it notifies between changes in check state but this is not really what I want.

**Comment by cuu508** [comment] 2022-06-10 14:39
I'm using the hourly reminders feature to get reminded about checks that are down: 

![image](https://user-images.githubusercontent.com/661859/173089187-4a77b024-2ecd-4fcf-a3f7-47c12fb53925.png)

The hourly reminders are annoying but that's exactly the point. They annoy you until you fix the problem one way or another (pause the check, or run the job manually, but ideally fix the underlying issue so the problem does not happen again after a hour, day or week).

Wouldn't this feature work for you? If not, why not?

**Comment by PAI5REECHO** [comment] 2022-06-11 18:34
Say I have backups scheduled to run every 5 days, if a backup fails and I'm okay with that I get a notification, 5 days later when it fails again I get no notification. If I used hourly or daily reminders then I'd be getting spammed with something I'm already okay with having failed. I'd like the check state to reset just before the next cron interval so I get additional notifications every 5 days if they continue to fail.

**Comment by cuu508** [comment] 2022-06-13 06:43
Here's what I would do in this scenario:

* I have hourly reminders enabled. When the backup fails, I receive a "backup xyz is DOWN" notification. After that I start receiving a reminder every hour.
* After a few reminders I'm annoyed enough that I sit down to figure out what has happened. I find and fix the root cause of the failure. Then I either:
    * trigger the backup job manually, it completes with no errors, the check goes back to green, reminders stop
    * manually send a ping signal to make the check go green (e.g. by pressing the "Ping!" button in check's details page)

**Comment by PAI5REECHO** [comment] 2022-06-14 05:46
> - trigger the backup job manually, it completes with no errors, the check goes back to green, reminders stop
> manually send a ping signal to make the check go green (e.g. by pressing the "Ping!" button in check's details page)

Neither of these is automatic. I might go on vacation for a few weeks and come back to find 500 or 21 failure notifications when really I should have only have 4.

**Comment by PAI5REECHO** [comment] 2022-06-16 10:06
I've configured hourly Email Reports in my account settings but this doesn't do anything as I'm using Gotify for my notifications, not E-Mail. I'm on a self-hosted instance so E-Mail is out of the question

**Comment by cuu508** [comment] 2022-06-19 14:02
Duplicate of #510

**Closed by cuu508** 2022-06-19 14:02 UTC
