### ISSUE TITLE
Feature request: Google chat integration

### ISSUE THREAD

**Issue by SemihMFX** [healthchecks/healthchecks#883] opened 2023-08-21 14:34 UTC
We use Google Chat for our main communication. I noticed that other monitoring services use google chat integration for notifications that get send in a certain channel whenever a check goes down. Would it be possible to have Google Chat integration?

**Comment by cuu508** [comment] 2023-08-21 15:11
Duplicate of #423

**Closed by cuu508** 2023-08-21 15:11 UTC
