### ISSUE TITLE
Ability to set minimum time between start and end

### ISSUE THREAD

**Issue by jetchirag** [healthchecks/healthchecks#560] opened 2021-09-21 14:19 UTC
Hello,

This would be useful in cases where a job takes atleast specific time such as backups. Instead of having to deal with fail scenarios in simple scripts, it would be great if could just set X minimum time for it to run, otherwise consider it failed.

**Comment by cuu508** [comment] 2022-06-20 05:53
Duplicate of #236

**Closed by cuu508** 2022-06-20 05:53 UTC
Labels: feature
